services:
  - type: web
    name: voice-character-matcher
    env: python
    runtime: python-3.11.0
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn app:app --timeout 120 --workers 1"
    envVars:
      - key: FLASK_DEBUG
        value: false

